baseURL = "http://linton-dawson.github.io/"
languageCode = "en-us"
title = "#include<pushkars_blabber.h>"
theme = "hello-friend-ng"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Subtitle for home
  homeSubtitle = "will randomly write random posts on random things in random order."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "Pushkar's blog"
  keywords = "homepage, blog"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # Default theme "light" or "dark"
  defaultTheme = "dark"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

  [[params.social]]
    name = "email"
    url  = "mailto:pushkarkukde@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/linton-dawson"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/pushkar-kukde"

  [[params.social]]
    name = "codechef"
    url = "https://www.codechef.com/users/linton_dawson"

[languages]
  [languages.en]
    title = "Pushkar Kukde"
    subtitle = "pushkar's blog"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cd ~/linton_dawson/"
      logoHomeLink = "/"
    # or
    #
    # path = "/static/pkphoto.svg"
    # alt = "myphoto"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "blog"
    url        = "/posts"
